# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyloftserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
