# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyloftserver', '0004_auto_20170424_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbook',
            name='commercial_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='demo', max_length=200),
        ),
    ]
