# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copyloftserver', '0005_auto_20170427_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='covers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='copyloftserver.Cover'),
        ),
    ]
