# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyloftserver', '0008_auto_20170429_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='inktype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='inktype',
            name='name',
            field=models.CharField(default='demo', max_length=200),
        ),
    ]
